# -*- coding: utf-8 -*-
"""Pix2pix-easy implementation

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mw1IH5OJU4U2MU6nOMeJj19cAjRXXZay

This implementation is easier than the one provided by the original author!

ref: https://github.com/mrzhu-cool/pix2pix-pytorch

ref: https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix
"""

# download the facade dataset:
import os

if os.path.isdir("/content/facades/") == False:
  os.system("gdown https://drive.google.com/uc?id=1GYxTh39YfF80rU8gnEtfuVebA44zb4SU") # please remind that executing unzip using os.system() won't let you see the unzip message
  os.system("unzip facades.zip")
  os.remove("facades.zip")






img1 = cv2.imread('result/facades/cmp_x0060.png')
img2 = cv2.imread('result/facades/cmp_b0148.png')

cv2_imshow(img1)
cv2_imshow(img2)